- name: configuring frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: enable nginx1.24
    command: dnf module enable nginx:1.24 -yes
  - name: install nginx
    package:
      name: nginx
      state: present
  - name: remove html directory
    file: 
      path: /usr/share/nginx/html/
      sateat: absent
  - name: create html directory
    file:
      path: /usr/share/nginx/html/
      state: directory
